language: python
python: 2.7
env:
  - TOXENV=py27
install:
  - pip install -U tox
script: tox
notifications:
  irc:
    use_notice: true
    skip_join: true
    channels:
      - irc.freenode.org#scrapy
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapy
  password:
    secure: sCcSmDXy2F9H0b5p/Q3+KqPQp3UpqepyBHh7s7yGfNkMb6HgDjvER28AmUuDxUb+zgQ0WL7jqSZvrzAnbe3JTmjNHL3hFywLKFjNmjHIV+I2h+xDz2xjPs2gwtIBOs8AVMgqq0mqigZzlJssdzDlgVLYJ3Nf+vVwDGT5fR72byI=
  on:
    tags: true
    all_branches: true
    repo: scrapy/scrapy-djangoitem
    condition: "$TOXENV == py27"
